# Generated by Django 5.1.4 on 2025-01-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='elevation_gain',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_difficulty_level', to='walks.walk')),
            ],
        ),
        migrations.AddField(
            model_name='walk',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walk_difficulty_level', to='walks.difficultylevel'),
        ),
    ]
