# Generated by Django 5.1.4 on 2025-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_remove_difficultylevel_walk'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
