# Generated by Django 5.1.4 on 2025-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_walk_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
