# Generated by Django 5.1.4 on 2025-01-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0005_alter_walk_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='map_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
