# Generated by Django 5.1.4 on 2025-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0006_alter_walk_map_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
