# Generated by Django 5.1.4 on 2025-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0007_walk_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='featured_img',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
