# Generated by Django 5.1.4 on 2025-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('elevation', models.FloatField()),
                ('time_taken', models.TimeField()),
                ('route_img', models.ImageField(upload_to='static/images/')),
                ('comments', models.TextField()),
            ],
        ),
    ]
