# Generated by Django 5.1.4 on 2025-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_route_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
