# Generated by Django 5.1.4 on 2025-01-15 14:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_distance_alter_route_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_taken',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
