# Generated by Django 5.1.4 on 2025-01-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_comments_alter_route_route_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='time_taken',
        ),
    ]
