# Generated by Django 5.1.4 on 2025-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_remove_route_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
