# Generated by Django 5.1.4 on 2025-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_route_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='elevation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
